# Generated by Django 3.1.4 on 2021-10-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20210828_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='owner',
            field=models.CharField(max_length=125),
        ),
    ]
