# Generated by Django 3.1.4 on 2021-10-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auto_20211028_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='image',
            field=models.ImageField(upload_to='nameFile'),
        ),
    ]
