# Generated by Django 3.1.4 on 2021-12-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
