# Generated by Django 3.1.4 on 2021-12-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_auto_20211201_1738'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bid',
            new_name='BidModel',
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentModel',
        ),
    ]
